name: Sync Docs

on:
  push:
    paths:
      - 'package.json'
      - 'docs-site/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs-site

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies (Root)
        run: pnpm install --no-frozen-lockfile
        working-directory: .

      - name: Install Dependencies (docs-site)
        run: pnpm install --no-frozen-lockfile

      - name: Get Golden Layout Version
        id: glver
        run: echo "GL_VERSION=$(jq -r '.dependencies["golden-layout"]' ../package.json | tr -d '^~')" >> $GITHUB_OUTPUT
        working-directory: .

      # Skip Golden Layout Docs for now
      - name: Create Golden Layout Docs Directory
        run: mkdir -p ../docs-site/static/docs/golden-layout/2.6.0

      # Skip API Docs for now
      - name: Create API Docs Directory
        run: mkdir -p ../docs-site/docs/api
      - name: Version Docusaurus Docs
        if: steps.glver.outputs.GL_VERSION != ''
        run: npm run docusaurus docs:version ${{ steps.glver.outputs.GL_VERSION }}

      - name: Build Docusaurus Site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site/build
          destination_dir: docs  # 문서를 /docs 경로에 배포
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy documentation from ${{ github.repository }}@${{ github.sha }}'
          full_commit_message: 'Deploy documentation from ${{ github.repository }}@${{ github.sha }}'
